**CS210 Project Cleanup Notebook**

Here we are cleaning the data and preparing it for out project.  The goal is to take the large 2024 flight dataset(1.2gb) filter it down to ATL realted flights, clean the important fileds, and join it with Atlanta weather data, saving it into one final dataset that we can use for our visualization and modeling

**Connects Google Drice and checks the source file**

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

import os

input_file = "/content/drive/MyDrive/flight_data_2024.csv"
output_file = "/content/drive/MyDrive/atl_flights_2024.csv"

print("File exists:", os.path.exists(input_file))

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
File exists: True

# **Filter the national flight dataset doen to only ATL Flights**

The entire Flight dataset was way to big so we will only focus on the section relating to ATL airport and filter out all other airports

In [ ]:
import pandas as pd

input_file = "/content/drive/MyDrive/flight_data_2024.csv"
output_file = "/content/drive/MyDrive/atl_flights_2024.csv"

wanted_cols = [
    "year",
    "month",
    "day_of_month",
    "day_of_week",
    "fl_date",
    "op_unique_carrier",
    "op_carrier_fl_num",
    "origin",
    "origin_city_name",
    "origin_state_nm",
    "dest",
    "dest_city_name",
    "dest_state_nm",
    "crs_dep_time",
    "dep_time",
    "dep_delay",
    "taxi_out",
    "wheels_off",
    "wheels_on",
    "taxi_in",
    "crs_arr_time",
    "arr_time",
    "arr_delay",
    "cancelled",
    "cancellation_code",
    "diverted",
    "crs_elapsed_time",
    "actual_elapsed_time",
    "air_time",
    "distance",
    "carrier_delay",
    "weather_delay",
    "nas_delay",
    "security_delay",
    "late_aircraft_delay"
]

first_chunk = True
chunk_num = 0

for chunk in pd.read_csv(input_file, chunksize=100000):
    chunk_num += 1

    cols = [c for c in wanted_cols if c in chunk.columns]
    chunk = chunk[cols]

    atl_chunk = chunk[(chunk["origin"] == "ATL") | (chunk["dest"] == "ATL")]

    atl_chunk.to_csv(
        output_file,
        mode="w" if first_chunk else "a",
        index=False,
        header=first_chunk
    )

    first_chunk = False
    print(f"Finished chunk {chunk_num}, kept {len(atl_chunk)} rows")

print("Done. Saved ATL-only file to:", output_file)

Finished chunk 1, kept 9588 rows
Finished chunk 2, kept 8873 rows
Finished chunk 3, kept 9862 rows
Finished chunk 4, kept 10280 rows
Finished chunk 5, kept 9222 rows
Finished chunk 6, kept 9827 rows

/tmp/ipykernel_5855/821392348.py:47: DtypeWarning: Columns (24) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(input_file, chunksize=100000):

Finished chunk 7, kept 9889 rows

/tmp/ipykernel_5855/821392348.py:47: DtypeWarning: Columns (24) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(input_file, chunksize=100000):

Finished chunk 8, kept 9627 rows

/tmp/ipykernel_5855/821392348.py:47: DtypeWarning: Columns (24) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(input_file, chunksize=100000):

Finished chunk 9, kept 8963 rows

/tmp/ipykernel_5855/821392348.py:47: DtypeWarning: Columns (24) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(input_file, chunksize=100000):

Finished chunk 10, kept 10281 rows
Finished chunk 11, kept 9103 rows
Finished chunk 12, kept 9419 rows
Finished chunk 13, kept 10388 rows
Finished chunk 14, kept 9421 rows
Finished chunk 15, kept 9360 rows
Finished chunk 16, kept 9580 rows
Finished chunk 17, kept 9428 rows
Finished chunk 18, kept 9637 rows
Finished chunk 19, kept 10394 rows

/tmp/ipykernel_5855/821392348.py:47: DtypeWarning: Columns (24) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(input_file, chunksize=100000):

Finished chunk 20, kept 9693 rows
Finished chunk 21, kept 9541 rows
Finished chunk 22, kept 9684 rows
Finished chunk 23, kept 9810 rows
Finished chunk 24, kept 9582 rows

/tmp/ipykernel_5855/821392348.py:47: DtypeWarning: Columns (24) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(input_file, chunksize=100000):

Finished chunk 25, kept 9833 rows
Finished chunk 26, kept 10826 rows

/tmp/ipykernel_5855/821392348.py:47: DtypeWarning: Columns (24) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(input_file, chunksize=100000):

Finished chunk 27, kept 9793 rows
Finished chunk 28, kept 9405 rows
Finished chunk 29, kept 9789 rows
Finished chunk 30, kept 9612 rows
Finished chunk 31, kept 9834 rows
Finished chunk 32, kept 8677 rows
Finished chunk 33, kept 9746 rows
Finished chunk 34, kept 9818 rows
Finished chunk 35, kept 9164 rows
Finished chunk 36, kept 8996 rows
Finished chunk 37, kept 9846 rows
Finished chunk 38, kept 9728 rows
Finished chunk 39, kept 9966 rows

/tmp/ipykernel_5855/821392348.py:47: DtypeWarning: Columns (24) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(input_file, chunksize=100000):

Finished chunk 40, kept 9190 rows
Finished chunk 41, kept 9091 rows
Finished chunk 42, kept 9815 rows
Finished chunk 43, kept 9612 rows
Finished chunk 44, kept 9658 rows
Finished chunk 45, kept 9577 rows
Finished chunk 46, kept 9487 rows
Finished chunk 47, kept 9162 rows
Finished chunk 48, kept 9562 rows
Finished chunk 49, kept 9184 rows
Finished chunk 50, kept 9790 rows

/tmp/ipykernel_5855/821392348.py:47: DtypeWarning: Columns (24) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(input_file, chunksize=100000):

Finished chunk 51, kept 9928 rows
Finished chunk 52, kept 9772 rows
Finished chunk 53, kept 9908 rows
Finished chunk 54, kept 10170 rows
Finished chunk 55, kept 9470 rows

/tmp/ipykernel_5855/821392348.py:47: DtypeWarning: Columns (24) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(input_file, chunksize=100000):

Finished chunk 56, kept 9895 rows

/tmp/ipykernel_5855/821392348.py:47: DtypeWarning: Columns (24) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(input_file, chunksize=100000):

Finished chunk 57, kept 9944 rows
Finished chunk 58, kept 9905 rows
Finished chunk 59, kept 8845 rows
Finished chunk 60, kept 9543 rows

/tmp/ipykernel_5855/821392348.py:47: DtypeWarning: Columns (24) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(input_file, chunksize=100000):

Finished chunk 61, kept 8994 rows

/tmp/ipykernel_5855/821392348.py:47: DtypeWarning: Columns (24) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(input_file, chunksize=100000):

Finished chunk 62, kept 9794 rows

/tmp/ipykernel_5855/821392348.py:47: DtypeWarning: Columns (24) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(input_file, chunksize=100000):

Finished chunk 63, kept 10761 rows

/tmp/ipykernel_5855/821392348.py:47: DtypeWarning: Columns (24) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(input_file, chunksize=100000):

Finished chunk 64, kept 9268 rows
Finished chunk 65, kept 10791 rows
Finished chunk 66, kept 9626 rows
Finished chunk 67, kept 9696 rows

/tmp/ipykernel_5855/821392348.py:47: DtypeWarning: Columns (24) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(input_file, chunksize=100000):

Finished chunk 68, kept 11027 rows
Finished chunk 69, kept 9528 rows
Finished chunk 70, kept 8963 rows
Finished chunk 71, kept 7313 rows
Done. Saved ATL-only file to: /content/drive/MyDrive/atl_flights_2024.csv

# **Clean ATL Flight File**

taking the ATL only flights we are converting the cols into the proper data types, making sure missing values are delt with and removing duplications of data

In [ ]:
#CLEAN THE DATA
import numpy as np

input_file = "/content/drive/MyDrive/atl_flights_2024.csv"
output_file = "/content/drive/MyDrive/atl_flights_2024_cleaned.csv"

df = pd.read_csv(input_file, low_memory=False)

# Basic date cleanup
df["fl_date"] = pd.to_datetime(df["fl_date"], errors="coerce")

# Remove duplicates
df = df.drop_duplicates()

# Convert numeric columns
numeric_cols = [
    "year", "month", "day_of_month", "day_of_week",
    "op_carrier_fl_num",
    "crs_dep_time", "dep_time", "dep_delay",
    "taxi_out", "wheels_off", "wheels_on", "taxi_in",
    "crs_arr_time", "arr_time", "arr_delay",
    "cancelled", "diverted",
    "crs_elapsed_time", "actual_elapsed_time", "air_time", "distance",
    "carrier_delay", "weather_delay", "nas_delay",
    "security_delay", "late_aircraft_delay"
]

for col in numeric_cols:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors="coerce")

# Clean text columns
text_cols = [
    "op_unique_carrier", "origin", "origin_city_name", "origin_state_nm",
    "dest", "dest_city_name", "dest_state_nm", "cancellation_code"
]

for col in text_cols:
    if col in df.columns:
        df[col] = df[col].astype(str).str.strip()

# Fix placeholder text values
if "cancellation_code" in df.columns:
    df.loc[df["cancellation_code"].isin(["nan", "None", "NaN"]), "cancellation_code"] = np.nan

# Fill some basic flag columns
if "cancelled" in df.columns:
    df["cancelled"] = df["cancelled"].fillna(0).astype(int)

if "diverted" in df.columns:
    df["diverted"] = df["diverted"].fillna(0).astype(int)

# Fill delay breakdown columns only
delay_breakdown_cols = [
    "carrier_delay", "weather_delay", "nas_delay",
    "security_delay", "late_aircraft_delay"
]

for col in delay_breakdown_cols:
    if col in df.columns:
        df[col] = df[col].fillna(0)

# Drop rows missing core identifiers
df = df.dropna(subset=["fl_date", "origin", "dest", "op_unique_carrier"])

df.to_csv(output_file, index=False)

print("Done. Saved cleaned file to:", output_file)
print("Rows:", len(df))
print("Columns:", len(df.columns))
print(df.head())

Done. Saved cleaned file to: /content/drive/MyDrive/atl_flights_2024_cleaned.csv
Rows: 683754
Columns: 35
   year  month  day_of_month  day_of_week    fl_date op_unique_carrier  \
0  2024      1             1            1 2024-01-01                9E
1  2024      1             1            1 2024-01-01                9E
2  2024      1             1            1 2024-01-01                9E
3  2024      1             1            1 2024-01-01                9E
4  2024      1             1            1 2024-01-01                9E

   op_carrier_fl_num origin origin_city_name origin_state_nm  ... diverted  \
0             4858.0    ATL      Atlanta, GA         Georgia  ...        0
1             4858.0    TLH  Tallahassee, FL         Florida  ...        0
2             4910.0    ATL      Atlanta, GA         Georgia  ...        0
3             4910.0    DHN       Dothan, AL         Alabama  ...        0
4             4912.0    DHN       Dothan, AL         Alabama  ...        0

  crs_elapsed_time actual_elapsed_time  air_time  distance  carrier_delay  \
0             69.0                68.0      43.0     223.0              0
1             71.0                63.0      44.0     223.0              0
2             66.0                56.0      34.0     170.0              0
3             76.0                60.0      36.0     170.0              0
4             66.0                82.0      33.0     170.0              0

   weather_delay  nas_delay  security_delay  late_aircraft_delay
0              0          0               0                    0
1              0          0               0                    0
2              0          0               0                    0
3              0          0               0                    0
4              0          0               0                    0

[5 rows x 35 columns]

# **Compare File Size before / after**

This part is a quick check to compare the raw ATL only data with teh cleaned ATL data.  Here you can see the data hasnt changed meaning there weren't any duplicates or missing values so the data file stayed the same size

In [ ]:
#Code to compare overall size of files before and after cleaning
raw_file = "/content/drive/MyDrive/atl_flights_2024.csv"
clean_file = "/content/drive/MyDrive/atl_flights_2024_cleaned.csv"

raw_df = pd.read_csv(raw_file, low_memory=False)
clean_df = pd.read_csv(clean_file, low_memory=False)

print("Raw rows:", len(raw_df))
print("Clean rows:", len(clean_df))
print("Raw columns:", len(raw_df.columns))
print("Clean columns:", len(clean_df.columns))

print("Raw size (MB):", os.path.getsize(raw_file) / (1024 * 1024))
print("Clean size (MB):", os.path.getsize(clean_file) / (1024 * 1024))

Raw rows: 683754
Clean rows: 683754
Raw columns: 35
Clean columns: 35
Raw size (MB): 118.76759624481201
Clean size (MB): 118.76759624481201

# **Keep only project cols**

After cleaning, we want make out file smaller and a little more managable still so we are narrowing the flight dataset down to just the cols we actaully want for the project.  This will make the file eaier to read and to use later in our visuals and models.

In [ ]:
#KEEP ONLY THE IMPORTANT COLUMNS

input_file = "/content/drive/MyDrive/atl_flights_2024_cleaned.csv"
output_file = "/content/drive/MyDrive/atl_flights_2024_project_ready.csv"

keep_cols = [
    "fl_date",
    "year",
    "month",
    "day_of_month",
    "day_of_week",
    "op_unique_carrier",
    "origin",
    "dest",
    "crs_dep_time",
    "crs_arr_time",
    "dep_delay",
    "arr_delay",
    "cancelled",
    "diverted",
    "carrier_delay",
    "weather_delay",
    "nas_delay",
    "security_delay",
    "late_aircraft_delay",
    "distance",
    "crs_elapsed_time"
]

df = pd.read_csv(input_file, low_memory=False)
cols = [c for c in keep_cols if c in df.columns]
df = df[cols]

df.to_csv(output_file, index=False)

print("Saved project-ready file to:", output_file)
print("Rows:", len(df))
print("Columns:", len(df.columns))

Saved project-ready file to: /content/drive/MyDrive/atl_flights_2024_project_ready.csv
Rows: 683754
Columns: 21

# **SQLite Load Fight data**

This starts our database.  We read the project ready flight CSV and store it as a SQL table so we can join it with the weather data and run SQL queries easily.

In [ ]:
#CREATE THE FLIGHT DATA TABLE
import sqlite3
flights = pd.read_csv("/content/drive/MyDrive/atl_flights_2024_project_ready.csv")
print(flights.head(5))
print(flights.columns)

drop_cols = [c for c in ["year", "fl_date", "day_of_week"] if c in flights.columns]
flights = flights.drop(columns=drop_cols)
print (flights.head(5))
print(flights.columns)

conn = sqlite3.connect("atl_project.db")
flights.to_sql("flights_atl", conn, if_exists="replace", index=False)
print("flights_atl table made")

pd.read_sql_query("SELECT * FROM flights_atl LIMIT 5;", conn)

# conn = sqlite3.connect("atl_projct.db")
# cur = conn.cursor()

# cur.execute ("CREATE TABLE IF NOT EXISITS flights_atl (fl_date DATE, year INT, month INT, day_of_month INT, day_of_week INT, op_unique_carrier TEXT, origin TEXT, dest TEXT, crs_dep_time INT, crs_arr_time INT, dep_delay NUMERIC, arr_delay NUMERIC, cancelled INT, diverted INT, carrier_delay NUMERIC, weather_delay NUMERIC, nas_delay NUMERIC, security_delay NUMERIC, late_aircraft_delay NUMERIC, distance NUMERIC, crs_elapsed_time NUMERIC);")

# conn.commit()

      fl_date  year  month  day_of_month  day_of_week op_unique_carrier  \
0  2024-01-01  2024      1             1            1                9E
1  2024-01-01  2024      1             1            1                9E
2  2024-01-01  2024      1             1            1                9E
3  2024-01-01  2024      1             1            1                9E
4  2024-01-01  2024      1             1            1                9E

  origin dest  crs_dep_time  crs_arr_time  ...  arr_delay  cancelled  \
0    ATL  TLH           920          1029  ...       -6.0          0
1    TLH  ATL          1114          1225  ...      -13.0          0
2    ATL  DHN          1355          1401  ...      -13.0          0
3    DHN  ATL          1446          1702  ...      -26.0          0
4    DHN  ATL           648           854  ...       10.0          0

   diverted  carrier_delay  weather_delay  nas_delay  security_delay  \
0         0              0              0          0               0
1         0              0              0          0               0
2         0              0              0          0               0
3         0              0              0          0               0
4         0              0              0          0               0

   late_aircraft_delay  distance  crs_elapsed_time
0                    0     223.0              69.0
1                    0     223.0              71.0
2                    0     170.0              66.0
3                    0     170.0              76.0
4                    0     170.0              66.0

[5 rows x 21 columns]
Index(['fl_date', 'year', 'month', 'day_of_month', 'day_of_week',
       'op_unique_carrier', 'origin', 'dest', 'crs_dep_time', 'crs_arr_time',
       'dep_delay', 'arr_delay', 'cancelled', 'diverted', 'carrier_delay',
       'weather_delay', 'nas_delay', 'security_delay', 'late_aircraft_delay',
       'distance', 'crs_elapsed_time'],
      dtype='object')
   month  day_of_month op_unique_carrier origin dest  crs_dep_time  \
0      1             1                9E    ATL  TLH           920
1      1             1                9E    TLH  ATL          1114
2      1             1                9E    ATL  DHN          1355
3      1             1                9E    DHN  ATL          1446
4      1             1                9E    DHN  ATL           648

   crs_arr_time  dep_delay  arr_delay  cancelled  diverted  carrier_delay  \
0          1029       -5.0       -6.0          0         0              0
1          1225       -5.0      -13.0          0         0              0
2          1401       -3.0      -13.0          0         0              0
3          1702      -10.0      -26.0          0         0              0
4           854       -6.0       10.0          0         0              0

   weather_delay  nas_delay  security_delay  late_aircraft_delay  distance  \
0              0          0               0                    0     223.0
1              0          0               0                    0     223.0
2              0          0               0                    0     170.0
3              0          0               0                    0     170.0
4              0          0               0                    0     170.0

   crs_elapsed_time
0              69.0
1              71.0
2              66.0
3              76.0
4              66.0
Index(['month', 'day_of_month', 'op_unique_carrier', 'origin', 'dest',
       'crs_dep_time', 'crs_arr_time', 'dep_delay', 'arr_delay', 'cancelled',
       'diverted', 'carrier_delay', 'weather_delay', 'nas_delay',
       'security_delay', 'late_aircraft_delay', 'distance',
       'crs_elapsed_time'],
      dtype='object')
flights_atl table made

,month,day_of_month,op_unique_carrier,origin,dest,crs_dep_time,crs_arr_time,dep_delay,arr_delay,cancelled,diverted,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay,distance,crs_elapsed_time
0,1,1,9E,ATL,TLH,920,1029,-5.0,-6.0,0,0,0,0,0,0,0,223.0,69.0
1,1,1,9E,TLH,ATL,1114,1225,-5.0,-13.0,0,0,0,0,0,0,0,223.0,71.0
2,1,1,9E,ATL,DHN,1355,1401,-3.0,-13.0,0,0,0,0,0,0,0,170.0,66.0
3,1,1,9E,DHN,ATL,1446,1702,-10.0,-26.0,0,0,0,0,0,0,0,170.0,76.0
4,1,1,9E,DHN,ATL,648,854,-6.0,10.0,0,0,0,0,0,0,0,170.0,66.0

# **Prepare/Load Weather Data**

Import the Atlanta weather dataset, convert the month names into numeric values for proper joining, and laod the weahter data into SQLite.  This is so the weather table matches the flight table more cleanly when joined

In [ ]:
#IMPORT THE WEATHER DATASET AND CREATE NUMERIC MONTH VALUES

weather = pd.read_csv("/content/drive/MyDrive/atlanta_2024_weather_daily.csv")

change_month = {
    "jan": 1, "feb": 2, "mar": 3, "apr": 4, "may": 5, "jun": 6, "jul": 7, "aug": 8, "sep": 9, "oct": 10, "nov": 11, "dec": 12
}
weather['Month_num'] = weather["Month"].str.lower().map(change_month)
weather = weather.drop(columns=["Month"])

#TURN THE WEATHER DATA INTO A SQL TABLE
conn = sqlite3.connect("atl_project.db")

weather.to_sql("weather_atl", conn, if_exists="replace", index=False)
print("weather_atl table made")

pd.read_sql_query("SELECT * FROM weather_atl LIMIT 5;", conn)

weather_atl table made

,Day,Temp_Max_F,Temp_Avg_F,Temp_Min_F,DewPoint_Max_F,DewPoint_Avg_F,DewPoint_Min_F,Humidity_Max_pct,Humidity_Avg_pct,Humidity_Min_pct,Wind_Max_mph,Wind_Avg_mph,Wind_Min_mph,Pressure_Max_in,Pressure_Avg_in,Pressure_Min_in,Precip_Total_in,Month_num
0,1,49,42.4,34,34,29.4,24,76,60.5,44,17,11.0,5,29.1,29.0,29.0,0.00,1
1,2,53,40.4,30,27,25.3,24,79,57.8,32,9,6.2,0,29.2,29.1,29.1,0.00,1
2,3,47,39.0,31,36,29.8,25,86,70.8,52,9,5.2,0,29.1,29.0,28.9,0.00,1
3,4,52,41.3,34,32,28.8,26,82,63.3,38,15,9.6,5,29.1,29.0,28.9,0.03,1
4,5,53,42.2,32,38,27.8,23,82,58.4,37,16,11.3,5,29.2,29.1,28.9,0.00,1

# **Join Flight and Weather Tables**

Here we are joining the cleaned flight table and the weather table using month and day.  Once this is done each flight row also has the corresponding weather info for that same day in ATL.

In [ ]:
#CONNECT THE TWO TABLES TOGETHER
weather.to_sql("weather_atl", conn, if_exists="replace", index=False)
flights.to_sql("flights_atl", conn, if_exists="replace", index=False)
query = """
CREATE TABLE IF NOT EXISTS joined_atl AS
SELECT *
FROM flights_atl flights
JOIN weather_atl weather
  ON flights.day_of_month = weather.Day
  AND flights.month = weather.Month_num;
"""
cursor = conn.cursor()
cursor.execute(query)
conn.commit()

pd.read_sql_query("SELECT * FROM joined_atl LIMIT 5;", conn)

,month,day_of_month,op_unique_carrier,origin,dest,crs_dep_time,crs_arr_time,dep_delay,arr_delay,cancelled,...,Humidity_Avg_pct,Humidity_Min_pct,Wind_Max_mph,Wind_Avg_mph,Wind_Min_mph,Pressure_Max_in,Pressure_Avg_in,Pressure_Min_in,Precip_Total_in,Month_num
0,1,1,9E,ATL,TLH,920,1029,-5.0,-6.0,0,...,60.5,44,17,11.0,5,29.1,29.0,29.0,0.0,1
1,1,1,9E,TLH,ATL,1114,1225,-5.0,-13.0,0,...,60.5,44,17,11.0,5,29.1,29.0,29.0,0.0,1
2,1,1,9E,ATL,DHN,1355,1401,-3.0,-13.0,0,...,60.5,44,17,11.0,5,29.1,29.0,29.0,0.0,1
3,1,1,9E,DHN,ATL,1446,1702,-10.0,-26.0,0,...,60.5,44,17,11.0,5,29.1,29.0,29.0,0.0,1
4,1,1,9E,DHN,ATL,648,854,-6.0,10.0,0,...,60.5,44,17,11.0,5,29.1,29.0,29.0,0.0,1

# **Helper Cols for Testing**

With the Joined tables we can add a few cols that will be used ater in the model and help with analysis.  These are delay indicator cols, a weather severity flag, and a scheduled departure hour col.

In [ ]:
#Create columns for testing
cursor = conn.cursor()

cursor.execute("ALTER TABLE joined_atl ADD COLUMN dep_delayed_15 INTEGER;")
cursor.execute("ALTER TABLE joined_atl ADD COLUMN arr_delayed_15 INTEGER;")
cursor.execute("ALTER TABLE joined_atl ADD COLUMN weather_severity_flag INTEGER;")
cursor.execute("ALTER TABLE joined_atl ADD COLUMN sched_dep_hour INTEGER;")
conn.commit()
print("This worked *thumbs up*")

This worked *thumbs up*

# **Values for Helper Cols**

This section updates the helper cols we created above.  It makrs flights with delays over 15 mins, and creates a simple weather severity flag case (will be used to predict if weather will delay flights)

In [ ]:
#Create severity flags
pd.read_sql_query("SELECT * FROM joined_atl LIMIT 5;", conn)

cursor.execute("""
    UPDATE joined_atl
    SET
      dep_delayed_15 = CASE
        WHEN cancelled = 0 AND dep_delay > 15 THEN 1
        ELSE 0
      END,
      arr_delayed_15 = CASE
        WHEN cancelled = 0 AND arr_delay > 15 THEN 1
        ELSE 0
      END,
      weather_severity_flag = CASE
        WHEN Precip_Total_in > 1.25 OR Wind_Avg_mph >= 15 THEN 1
        ELSE 0
      END,
      sched_dep_hour = CAST(crs_dep_time / 100 AS INTEGER);
""")
conn.commit()
print("This worked *thumbs up* p2")
pd.read_sql_query("SELECT * FROM joined_atl LIMIT 100;", conn)

This worked *thumbs up* p2

,month,day_of_month,op_unique_carrier,origin,dest,crs_dep_time,crs_arr_time,dep_delay,arr_delay,cancelled,...,Wind_Min_mph,Pressure_Max_in,Pressure_Avg_in,Pressure_Min_in,Precip_Total_in,Month_num,dep_delayed_15,arr_delayed_15,weather_severity_flag,sched_dep_hour
0,1,1,9E,ATL,TLH,920,1029,-5.0,-6.0,0,...,5,29.1,29.0,29.0,0.0,1,0,0,0,9
1,1,1,9E,TLH,ATL,1114,1225,-5.0,-13.0,0,...,5,29.1,29.0,29.0,0.0,1,0,0,0,11
2,1,1,9E,ATL,DHN,1355,1401,-3.0,-13.0,0,...,5,29.1,29.0,29.0,0.0,1,0,0,0,13
3,1,1,9E,DHN,ATL,1446,1702,-10.0,-26.0,0,...,5,29.1,29.0,29.0,0.0,1,0,0,0,14
4,1,1,9E,DHN,ATL,648,854,-6.0,10.0,0,...,5,29.1,29.0,29.0,0.0,1,0,0,0,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1,1,9E,ATL,TYS,2110,2208,-14.0,-16.0,0,...,5,29.1,29.0,29.0,0.0,1,0,0,0,21
96,1,1,9E,ATL,AVL,1410,1511,-4.0,-17.0,0,...,5,29.1,29.0,29.0,0.0,1,0,0,0,14
97,1,1,9E,AVL,ATL,1556,1705,213.0,207.0,0,...,5,29.1,29.0,29.0,0.0,1,1,1,0,15
98,1,1,9E,LEX,ATL,600,742,-6.0,-28.0,0,...,5,29.1,29.0,29.0,0.0,1,0,0,0,6
99,1,1,9E,ATL,JAN,1845,1912,-4.0,-15.0,0,...,5,29.1,29.0,29.0,0.0,1,0,0,0,18

# **TEST**

Simple test to make sure joined table is wokring and the delay col was created properly

In [ ]:
#Test
pd.read_sql_query("""
SELECT *
FROM joined_atl
WHERE arr_delayed_15 = 1;
""", conn)

,month,day_of_month,op_unique_carrier,origin,dest,crs_dep_time,crs_arr_time,dep_delay,arr_delay,cancelled,...,Wind_Min_mph,Pressure_Max_in,Pressure_Avg_in,Pressure_Min_in,Precip_Total_in,Month_num,dep_delayed_15,arr_delayed_15,weather_severity_flag,sched_dep_hour
0,1,1,9E,AVL,ATL,1556,1705,213.0,207.0,0,...,5,29.1,29.0,29.0,0.0,1,1,1,0,15
1,1,1,9E,ATL,VLD,959,1114,25.0,16.0,0,...,5,29.1,29.0,29.0,0.0,1,1,1,0,9
2,1,1,AA,MIA,ATL,1902,2100,100.0,93.0,0,...,5,29.1,29.0,29.0,0.0,1,1,1,0,19
3,1,1,AA,ATL,DFW,1624,1759,79.0,53.0,0,...,5,29.1,29.0,29.0,0.0,1,1,1,0,16
4,1,1,AA,DFW,ATL,1910,2212,35.0,29.0,0,...,5,29.1,29.0,29.0,0.0,1,1,1,0,19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121495,12,31,WN,MIA,ATL,1630,1835,89.0,89.0,0,...,6,28.9,28.7,28.6,0.0,12,1,1,0,16
121496,12,31,WN,LGA,ATL,2045,2325,37.0,32.0,0,...,6,28.9,28.7,28.6,0.0,12,1,1,0,20
121497,12,31,WN,ATL,SRQ,1115,1250,-1.0,39.0,0,...,6,28.9,28.7,28.6,0.0,12,0,1,0,11
121498,12,31,WN,ATL,LGA,615,825,41.0,25.0,0,...,6,28.9,28.7,28.6,0.0,12,1,1,0,6
121499,12,31,WN,ATL,DEN,1655,1820,7.0,20.0,0,...,6,28.9,28.7,28.6,0.0,12,0,1,0,16

# **SQL summary: airlines with the highest average arrival delay**

This quert is one of our first checks.  It helps show which ariliens tend to have the highest average arrival delays in dataset.

In [ ]:
#See what airlines are the most likely to be delayed
pd.read_sql_query("""
SELECT
    op_unique_carrier,
    AVG(arr_delay) AS avg_arr_delay
FROM joined_atl
WHERE cancelled = 0
GROUP BY op_unique_carrier
ORDER BY avg_arr_delay DESC;
""", conn)

   op_unique_carrier  avg_arr_delay
0                 F9      19.733371
1                 AA      19.041290
2                 OO      17.427771
3                 B6      14.822143
4                 NK      14.101518
5                 OH      12.245449
6                 MQ      10.239080
7                 UA       7.292475
8                 AS       6.136573
9                 WN       5.609601
10                DL       3.970726
11                9E       2.538241
12                YX       1.610078

# **SQL summary: weather severity and disruption**

Looks at how the weather severity flag lines up with the delay and cancellation rates.  It give us an idea of whether weather conditions appear to matter in the joined data.

In [ ]:
#See what % of flights are cancelled due to having weather severity
#Correliation matrix scikit learn library  **TRY this approach**

pd.read_sql_query("""
SELECT
    weather_severity_flag,
    AVG(dep_delayed_15) AS dep_delayed_rate,
    AVG(arr_delayed_15) AS arr_delayed_rate,
    AVG(cancelled) AS cancellation_rate
FROM joined_atl
GROUP BY weather_severity_flag;
""", conn)

,weather_severity_flag,dep_delayed_rate,arr_delayed_rate,cancellation_rate
0,0,0.172061,0.170556,0.008702
1,1,0.250609,0.259927,0.027717

# **Save the final cleaned and joined Dataset**

In [ ]:
#Create a final CSV
final_df = pd.read_sql_query("SELECT * FROM joined_atl;", conn)
final_df.to_csv("/content/drive/MyDrive/atl_joined_weather_flights_2024.csv", index=False)
print("It saved")

It saved